# Generated by Django 4.2 on 2024-02-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ulasanbuku',
            fields=[
                ('ulasanid', models.IntegerField(db_column='UlasanID', primary_key=True, serialize=False)),
                ('ulasan', models.TextField(db_column='Ulasan')),
                ('rating', models.IntegerField(db_column='Rating')),
            ],
            options={
                'db_table': 'ulasanbuku',
                'managed': False,
            },
        ),
    ]
