# Generated by Django 3.0.5 on 2024-03-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulasanbuku', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ulasanbuku',
            options={},
        ),
    ]
