# Generated by Django 3.0.5 on 2024-03-11 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buku', '0004_buku_kategoriid'),
        ('ulasanbuku', '0002_auto_20240311_1530'),
    ]

    operations = [
    ]
