# Generated by Django 3.0.5 on 2024-03-11 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0004_buku_kategoriid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ulasanbuku', '0003_auto_20240311_1541'),
    ]

    operations = [
    ]
