# Generated by Django 3.0.5 on 2024-03-15 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buku', '0004_buku_kategoriid'),
        ('ulasanbuku', '0004_auto_20240311_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulasanbuku',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], db_column='Rating'),
        ),
    ]
