# Generated by Django 5.0.2 on 2024-03-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peminjaman',
            options={},
        ),
    ]
