# Generated by Django 5.0.2 on 2024-03-06 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0004_buku_kategoriid'),
        ('peminjaman', '0002_alter_peminjaman_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='peminjamanid',
            field=models.AutoField(db_column='PeminjamanID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='statuspeminjaman',
            field=models.CharField(choices=[('Dipinjam', 'Dipinjam'), ('Dikembalikan', 'Dikembalikan')], db_column='StatusPeminjaman', max_length=50),
        ),
    ]
