# Generated by Django 3.0.5 on 2024-03-08 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buku', '0004_buku_kategoriid'),
        ('peminjaman', '0003_peminjaman_bukuid_peminjaman_userid_and_more'),
    ]

    operations = [
    ]
