# Generated by Django 3.0.5 on 2024-03-10 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0004_buku_kategoriid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peminjaman', '0010_auto_20240310_2032'),
    ]

    operations = [
    ]
