# Generated by Django 4.2 on 2024-02-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Koleksipribadi',
            fields=[
                ('koleksiid', models.IntegerField(db_column='KoleksiID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'koleksipribadi',
                'managed': False,
            },
        ),
    ]
