# Generated by Django 3.0.5 on 2024-03-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koleksipribadi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='koleksipribadi',
            options={},
        ),
    ]
