# Generated by Django 3.0.5 on 2024-03-08 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0004_buku_kategoriid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('koleksipribadi', '0002_auto_20240308_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='koleksipribadi',
            name='bukuid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buku.Buku'),
        ),
        migrations.AddField(
            model_name='koleksipribadi',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='koleksipribadi',
            name='koleksiid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='koleksipribadi',
            unique_together={('userid', 'bukuid')},
        ),
        migrations.AlterModelTable(
            name='koleksipribadi',
            table=None,
        ),
    ]
