# Generated by Django 3.0.5 on 2024-03-10 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0004_buku_kategoriid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('koleksipribadi', '0004_auto_20240308_2331'),
    ]

    operations = [
    ]
