# Generated by Django 3.0.5 on 2024-03-15 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0004_buku_kategoriid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('koleksipribadi', '0013_auto_20240315_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koleksipribadi',
            name='koleksiid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
