# Generated by Django 4.2 on 2024-02-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('bukuid', models.IntegerField(db_column='BukuID', primary_key=True, serialize=False)),
                ('judul', models.CharField(db_column='Judul', max_length=255)),
                ('penulis', models.CharField(db_column='Penulis', max_length=255)),
                ('penerbit', models.CharField(db_column='Penerbit', max_length=255)),
                ('tahunterbit', models.IntegerField(db_column='TahunTerbit')),
            ],
            options={
                'db_table': 'buku',
                'managed': False,
            },
        ),
    ]
