# Generated by Django 5.0.2 on 2024-02-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buku',
            options={'managed': True},
        ),
    ]
