# Generated by Django 5.0.2 on 2024-02-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0002_alter_buku_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buku',
            options={},
        ),
        migrations.AddField(
            model_name='buku',
            name='tersedia',
            field=models.BooleanField(default=True),
        ),
    ]
