# Generated by Django 4.2 on 2024-02-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=255)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('email', models.CharField(db_column='Email', max_length=255)),
                ('namalengkap', models.CharField(db_column='NamaLengkap', max_length=255)),
                ('alamat', models.TextField(db_column='Alamat')),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
