# Generated by Django 5.0.2 on 2024-03-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
